#!/bin/bash

distrodiscord=$HOME"/.local/share/distro-discord"

neofetch
if [ $? = 127 ]
then
  echo "Please install neofetch. It is a very required dependency."
  echo
  echo "INSTALLATION:"
  echo "sudo apt install -y neofetch"
  echo "sudo pacman -S neofetch"
  echo "For other distros, please see your package manager's documentation."
  exit 127
fi

python3 --version
if [ $? = 127 ]
then
  echo "Please install python3. It is a very required dependency."
  echo
  echo "INSTALLATION:"
  echo "sudo apt install -y python3"
  echo "sudo pacman -S python3"
  echo "For other distros, please see your package manager's documentation."
  exit 127
fi

pip3 --version
if [ $? = 127 ]
then
  echo "Please install pip3. It is a required dependency."
  echo
  echo "INSTALLATION:"
  echo "sudo apt install -y python3-pip"
  echo "sudo pacman -S python-pip"
  echo "For other distros, please see your package manager's documentation."
  exit 127
fi

echo "Path to files: "$distrodiscord

if [ -d $distrodiscord ]
then
  cd $distrodiscord
else
  mkdir $distrodiscord
  cd $distrodiscord
  git clone https://github.com/Spiffily/distro-discord.git
fi

pip3 install pypresence
git pull

if [ $1 = "install" ]
then
  sudo cp $distrodiscord/distro-discord /usr/bin
  sudo chown root:root /usr/bin/distro-discord
  sudo chmod 755 /usr/bin/distro-discord
  exit 0
fi

echo
if [ -x $distrodiscord/distro-discord.py ]
then
  python3 $distrodiscord/distro-discord.py
else
  chmod +x $distrodiscord/distro-discord.py
  python3 $distrodiscord/distro-discord.py
fi
